# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20160129_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='owner',
        ),
    ]
